#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Generate ATAN test vectors from local python/model.py.

Reads NXP input stimuli from atan_cwproj/vector/in/TCxxx and computes
reference output with the local r_atan2 model.

Usage:
  python3 gen_vectors.py              # uses TC from env or TC001
  python3 gen_vectors.py --tc TC005
  python3 gen_vectors.py --all
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys

import numpy as np

_TESTS_DIR = Path(__file__).resolve().parent
_KERNEL_DIR = _TESTS_DIR.parent
_VSPA_LIB_DIR = _KERNEL_DIR.parent
_COMMON_PY = _VSPA_LIB_DIR / 'common' / 'python'

for p in (str(_COMMON_PY), str(_KERNEL_DIR / 'python')):
    if p not in sys.path:
        sys.path.insert(0, p)

from vspa.io import PREC_IDX, _float_to_sm16, read_complex_binary
from utils.hex_io import write_hex_u32
from model import r_atan2

VECTOR_ROOT = _KERNEL_DIR / 'atan_cwproj' / 'vector'
OUT_ROOT = _TESTS_DIR / 'vectors'

NUM_COEFF_LIST = [3, 4, 5, 6, 7, 8, 9, 10,
                  3, 4, 5, 6, 7, 8, 9, 10,
                  3, 4, 5, 6, 7, 8, 9, 10,
                  3, 4, 5, 6, 7, 8, 9, 10,
                  3, 4, 5, 6, 7, 8, 9, 10,
                  3, 4, 5, 6, 7, 8, 9, 10,
                  3, 4, 5, 6, 7, 8, 9, 10]


def _prepare_tc(tc_name: str) -> dict:
    tc_idx = int(tc_name[2:])
    tc_in = VECTOR_ROOT / 'in' / tc_name
    out_dir = OUT_ROOT / tc_name

    ctrl_path = tc_in / 'ctrl.bin'
    input_path = tc_in / 'input.bin'

    if not ctrl_path.exists() or not input_path.exists():
        raise FileNotFoundError(f'missing input vectors for {tc_name}')

    ctrl = np.frombuffer(ctrl_path.read_bytes(), dtype='<u4')
    input_len = int(ctrl[0])
    inp_prec = PREC_IDX[int(ctrl[1])]
    out_prec = PREC_IDX[int(ctrl[2])]
    num_coeff = NUM_COEFF_LIST[tc_idx]

    inp_complex = read_complex_binary(str(input_path), inp_prec)
    phase = np.asarray(
        r_atan2(inp_complex, inp_prec=inp_prec, out_prec=out_prec, num_coeff=num_coeff),
        dtype=np.float64,
    ).reshape(-1)

    in_raw = np.frombuffer(input_path.read_bytes(), dtype='<u4')
    phase_words = np.asarray(phase, dtype=np.float64)
    if out_prec == 'half_fixed':
        u16 = _float_to_sm16(phase_words).astype(np.uint16)
        ref_raw = u16.view(np.uint32)
    elif out_prec == 'half':
        u16 = phase_words.astype(np.float16).view(np.uint16)
        ref_raw = u16.view(np.uint32)
    elif out_prec == 'single':
        ref_raw = phase_words.astype(np.float32).view(np.uint32)
    else:
        raise ValueError(f'Unsupported out_prec: {out_prec}')

    out_dir.mkdir(parents=True, exist_ok=True)
    write_hex_u32(in_raw, str(out_dir / 'input.hex'))
    write_hex_u32(ctrl.astype(np.uint32), str(out_dir / 'ctrl.hex'))
    write_hex_u32(ref_raw, str(out_dir / 'reference.hex'))

    with (out_dir / 'tc_params.h').open('w') as f:
        f.write('// Auto-generated by tests/gen_vectors.py — DO NOT EDIT\n')
        f.write(f'#define TC_INPUT_LEN   {input_len}\n')
        f.write(f'#define TC_NUM_COEFF   {num_coeff}\n')
        f.write(f'#define TC_INP_PREC    {int(ctrl[1])}  // 0=half_fixed 1=half 2=single\n')
        f.write(f'#define TC_OUT_PREC    {int(ctrl[2])}  // 0=half_fixed 1=half 2=single\n')
        f.write(f'#define TC_N_INP_WORDS {len(in_raw)}\n')
        f.write(f'#define TC_N_REF_WORDS {len(ref_raw)}\n')

    return {
        'tc': tc_name,
        'input_len': input_len,
        'num_coeff': num_coeff,
        'inp_prec': inp_prec,
        'out_prec': out_prec,
        'n_inp_words': len(in_raw),
        'n_ref_words': len(ref_raw),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description='Generate ATAN vectors from local model')
    parser.add_argument('--tc', default=None, help='TC id, e.g. TC001')
    parser.add_argument('--all', action='store_true', help='Generate all available test cases')
    args = parser.parse_args()

    tc_env = str(os.environ.get('TC', 'TC001'))
    if args.all:
        tc_list = [f'TC{i:03d}' for i in range(56)]
    elif args.tc:
        tc_list = [args.tc]
    else:
        tc_list = [tc_env]

    for tc in tc_list:
        meta = _prepare_tc(tc)
        print(f"{meta['tc']}: len={meta['input_len']} coeff={meta['num_coeff']} "
              f"{meta['inp_prec']}->{meta['out_prec']} "
              f"inp={meta['n_inp_words']} ref={meta['n_ref_words']}")


if __name__ == '__main__':
    main()
