// Auto-generated by tests/gen_vectors.py — DO NOT EDIT
#define TC_INPUT_LEN   64
#define TC_NUM_COEFF   4
#define TC_INP_PREC    0  // 0=half_fixed 1=half 2=single
#define TC_OUT_PREC    0  // 0=half_fixed 1=half 2=single
#define TC_N_INP_WORDS 64
#define TC_N_REF_WORDS 32
