% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function dmemSaveTextFile(dmemIn, inFileName)
% Dmem access utility to generate text files (header files) with the
% content of a DMEM structure. This is suitable to generate LUT content for
% source code.
% INPUTS:
%
%   dmemIn:  struct representing DMEM.  Usually generated by a call to
%      dmemCreate().  Internal details of this structure only matter to
%      the dmem access layer implementation.
%
%   inFileName: string containing the name (and path if necessary) of the
%      text file to generate.
%
% SEE ALSO:
%      dmemCreate,
%      dmemWriteReal, dmemWriteComplex,
%      dmemReadReal,  dmemReadComplex,  dmemReadHexFile
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.
% dmemIn struct - for internal use:
%   base  ( full-word address pointing to first word )
%   data  ( vector holding storage data: one uint32 per memory location )

[fid, msg] = fopen(inFileName, 'wt');
if (-1 == fid)
    error(msg);
end

fprintf(fid, '0x%08x,\n', dmemIn.data(1 : end - 1));
fprintf(fid, '0x%08x \n', dmemIn.data(end));

fclose(fid);









