% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function dmem = dmemReadInitFile(filename, address, type, endAddress)
% Dmem access utility for reading the data memory image file generated by VSP
% ELF32 toolchain utility vspa-elf2hex.
%
% INPUTS:
%
%   filename: string containing the name (and path if necessary) of a
%       hex file generated by the vspa-elf2hex command line tool.
%
%   address (optional): start address for constant and initialized data.
%       Assumed to be zero if omitted.
%
%   type (optional): specifies how to initialize uninitialized data memory.
%       May be one of the following:
%         - 'zero' to initialize data memory to 0.
%         - 'random' to initialize data memory with random values.
%
%   endAddress (optional): end address to truncate the dmem image.
%
% OUTPUT:
%
%   dmem:  dmem image (dmem access layer structure) representing the data memory
%       (complete 131072 32-bit words (except when endAddress specified), where 
%				all values are random, except the ones initialized from <filename>.
%
% EXAMPLE USE:
%
%    Matlab:
%       ...
%       dram = dmemReadHexFile('vspa_vdata.hex', MEM__data_start, 'random' );
%       dram = dmemWriteReal( dram, MEM_variable, variable, 'uint' );
%       dram = dmemWriteComplex( dram, MEM_buffer, buffer, 'single' );
%       dmemSaveHexFile( dram, 'vspa_dram.hex' );
%       ...
%
% SEE ALSO:
%      dmemCreate,
%      dmemWriteReal, dmemWriteComplex, dmemSaveHexFile,
%      dmemReadReal,  dmemReadComplex
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.

if 1 == nargin
    address = 0;
    type = 'random';
elseif 2 == nargin
    type = 'random';
end

dmem = struct;
dmem.base = address;

[fid, msg] = fopen( filename, 'rt' );
if -1 == fid
    error( msg );
end
dataStrs = textscan( fid, '%8s\n' );
if strcmp( type, 'random' )
    dmem.data = randi( 2^32 - 1, 1007*128, 1 );
else
    dmem.data = zeros( 1007*128, 1 );
end
dmem.data(address+1:address+length( dataStrs{1} )) = hex2dec( dataStrs{1} );
if 4 == nargin
		dmem.data( endAddress : 1007*128 ) = [];
end
fclose( fid );

return;
