% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function dmemOut = dmemReadHexFile(outFileName, startAddr)
% Dmem access utility for reading dmemOut image from a hex file saved by
% the ISS from DMEM at the specified starting address using the "save dram"
% command.  Real or complex vectors of any precision can then be extracted
% from the dmemOut image using the dmemRead* utilities.
%
% INPUTS:
%
%   outFileName: string containing the name (and path if necessary) of a
%      hex file generated by the ISS from a "save dram" command.
%
%   startAddr:  full-word DMEM address (integer) pointing to the first word
%      of DMEM that was saved in the specified file.  This value should
%      match the starting address used in the ISS "save dram" command
%      that generated the hex file.
%
% OUTPUT:
%
%   dmemOut:  dmem image (dmem access layer structure) representing DMEM
%       contents extracted from the input file.
%
% EXAMPLE USE:
%    ISS Script:
%       ...
%       save dram outFileName   <startAddr>  <endAddr>
%       ...
%
%    Matlab:
%       ...
%       dramOut = dmemReadHexFile(outFileName, startAddr);
%       ...
%
% SEE ALSO:
%      dmemCreate,
%      dmemWriteReal, dmemWriteComplex, dmemSaveHexFile,
%      dmemReadReal,  dmemReadComplex
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.



% dmemIn struct - for internal use:
%   base  ( full-word address pointing to first word )
%   data  ( vector holding storage data: one uint32 per memory location )


dmemOut = struct;
dmemOut.base = startAddr;

[fid, msg] = fopen(outFileName, 'rt');
if -1 == fid
error( msg );
end
dataStrs = textscan(fid, '%8s\n');
dmemOut.data = hex2dec( dataStrs{1} );
fclose(fid);

return;




