% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function outputVec = dmemReadComplex(dmemIn, startAddr, numValues, precision)
% Dmem access utility for reading a complex vector out of dmemIn image at 
% the specified starting address using the specified precision.
%  
% INPUTS:
%
%   dmemIn:  struct representing DMEM.  Usually generated by a call to 
%      dmemCreate().  Internal details of this structure only matter to
%      the dmem access layer implementation.
%
%   startAddr:  full-word DMEM address (integer) pointing to the first word
%      of storage for inputVector.
%
%   numValues: number of complex values of the specified precision to read 
%      from DMEM.  The number of full-word memory locations read will 
%      depend on the precision.  For example, 
%           dmemReadComplex(dmemIn, 100, 10, 'double') 
%      would read 40 full-words to generate an outputVec containing 
%      10 complex doubles.
%
%   precision:  string specifying the precision to use when interpreting
%      the data in inputVector.  The options are:
%       'uint':  
%       'half_fixed':
%       'half':
%       'single':
%       'double':
%
% OUTPUT:
%
%   outputVec:  complex vector (numValues x 1) of matlab doubles
%      precision-limited according to specified precision
%
% EXAMPLE USE:
%   A typical calling sequence using the dmem access layer looks something
%   like this:
%       dram = dmemCreate(startAddr, MEM__ld_rodata_bottom);
%       dram = dmemWriteReal   (dram, MEM_x_buffer, x_be,   'half_fixed' );
%       dram = dmemWriteComplex(dram, MEM_y_buffer, y_be,   'single' );
%       dram = dmemWriteReal   (dram, MEM_ctrlVar, ctrlVar, 'uint' );
%       dmemSaveHexFile(dram, inFileName);
%       ... Run ISS ...
%             overwrite dram  <2*startAddr> inFileName
%             ...
%             save dram outFileName   <startAddr>  <endAddr>
%       dramOut = dmemReadHexFile( outFileName, startAddr );
%       x_mc = dmemReadReal   (dramOut, MEM_x_buffer, SIZ_x_buffer*2, 'half_fixed')
%       y_mc = dmemReadComplex(dramOut, MEM_y_buffer, SIZ_y_buffer/2, 'single' );
%
% SEE ALSO:
%      dmemCreate, 
%      dmemWriteReal, dmemWriteComplex, dmemSaveHexFile,
%      dmemReadReal,  dmemReadHexFile
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.
     


% dmemIn struct - for internal use:   
%   base  ( full-word address pointing to first word )
%   data  ( column vector holding storage data: one uint32 per memory location )


% Find the number of memory words required and verify that it fits

% Extract real vector and convert to complex
realVec   = dmemReadReal(dmemIn, startAddr, 2*numValues, precision);
outputVec = complex ( realVec(1:2:end),  realVec(2:2:end) );

return



    
    
    
    
    
    
