% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function dmemOut = dmemWriteReal(dmemIn, startAddr, inputVec, precision)
% Dmem access utility for writing the real inputVector into the dmemIn 
% image at the specified starting address using the specified precision.
%
% If the inputVector does not fit into the dmemIn image at startAddr, then
% dmemWriteReal issues an error().
%  
% INPUTS:
%
%   dmemIn:  struct representing DMEM.  Usually generated by a call to 
%      dmemCreate().  Internal details of this structure only matter to
%      the dmem access layer implementation.
%
%   startAddr:  full-word DMEM address (integer) pointing to the first word
%      of storage for inputVector.
%      
%   inputVec:  row or column vector of matlab doubles holding the data
%      to be written into DMEM at startAddr.  Each entry in inputVector
%      corresponds to one value of the specified precision.
%
%   precision:  string specifying the precision to use when interpreting
%      the data in inputVector.  The options are:
%       'uint':  
%       'half_fixed':
%       'half':
%       'single':
%       'double':
%
% OUTPUT:
%
%   dmemOut:  updated struct representing DMEM with inputVector loaded.
%
% EXAMPLE USE:
%   A typical calling sequence using the dmem access layer looks something
%   like this:
%       dram = dmemCreate(startAddr, MEM__ld_rodata_bottom);
%       dram = dmemWriteReal   (dram, MEM_x_buffer, x_be,   'half_fixed' );
%       dram = dmemWriteComplex(dram, MEM_y_buffer, y_be,   'single' );
%       dram = dmemWriteReal   (dram, MEM_ctrlVar, ctrlVar, 'uint' );
%       dmemSaveHexFile(dram, inFileName);
%       ... Run ISS ...
%             overwrite dram  <2*startAddr> inFileName
%             ...
%             save dram outFileName   <startAddr>  <endAddr>
%       dramOut = dmemReadHexFile( outFileName, startAddr );
%       x_mc = dmemReadReal   (dramOut, MEM_x_buffer, SIZ_x_buffer*2, 'half_fixed')
%       y_mc = dmemReadComplex(dramOut, MEM_y_buffer, SIZ_y_buffer/2, 'single' );
%
% SEE ALSO:
%      dmemCreate,    dmemWriteComplex, dmemSaveHexFile,
%      dmemReadReal,  dmemReadComplex,  dmemReadHexFile
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.
     


% dmemIn struct - for internal use:  
%   base  ( full-word address pointing to first word )
%   data  ( column vector holding storage data: one uint32 per memory location )


% Verify that inputVec is a vector and convert it to column form for use
if ( size(inputVec,1) ~= 1  && size(inputVec,2) ~= 1 )
    error('dmemWrite requires a row or column vector for inputVec');
end
if ( size(inputVec,2) > size(inputVec,1) )
    inputVec = inputVec.';  % convert from row to column vector
end


% Find the number of memory words required and verify that it fits
numWords = length(inputVec);
if strcmp(precision, 'half_fixed') || strcmp(precision, 'half')
    numWords = numWords/2;
end
if strcmp(precision, 'double')
    numWords = numWords*2;
end

startAddr = startAddr - dmemIn.base;   % convert startAddr to local address within image
if startAddr < 0
    error( sprintf('startAddr %d is not in image\n',startAddr) );
end
if (startAddr + numWords - 1) > length(dmemIn.data)
    error( sprintf('inputVec too large to load at startAddr %d\n',startAddr) );
end


% Generate dmemOut starting with a copy of dmemIn and filling the 
% specified startAadr location with inputVec based on precision setting
dmemOut = dmemIn;
startIndex = startAddr + 1;
endIndex   = startAddr + numWords;
switch precision
    case 'uint'
        dmemOut.data( startIndex:endIndex ) = uint32(inputVec);
        
    case 'half_fixed'
        x_rep = hex2dec([dec2hex(r_dbl2cust(inputVec(2:2:end), 0), 4) dec2hex(r_dbl2cust(inputVec(1:2:end), 0), 4)]);
        dmemOut.data( startIndex:endIndex ) = x_rep;      
        
    case 'half'
        x_rep = hex2dec([dec2hex(r_dbl2cust(inputVec(2:2:end), 1), 4) dec2hex(r_dbl2cust(inputVec(1:2:end), 1), 4)]);
        dmemOut.data( startIndex:endIndex ) = x_rep;
        
    case 'single'
        dmemOut.data( startIndex:endIndex ) = typecast( single( r_single(inputVec) ) , 'uint32');

    case 'double'
        dmemOut.data( startIndex:endIndex )  = typecast( r_double(inputVec),'uint32');
        
    otherwise
        error('unrecognized precision');
end

return



    
    
    
    
    
    
