% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function dmemOut = dmemWriteComplex(dmemIn, startAddr, inputVec, precision)
% Dmem access utility for writing the complex inputVector into the dmemIn 
% image at the specified starting address using the specified precision.
%
% If the inputVector does not fit into the dmemIn image at startAddr, then
% dmemWriteComplex issues an error().
%  
% INPUTS:
%
%   dmemIn:  struct representing DMEM.  Usually generated by a call to 
%      dmemCreate().  Internal details of this structure only matter to
%      the dmem access layer implementation.
%
%   startAddr:  full-word DMEM address (integer) pointing to the first word
%      of storage for inputVector.
%      
%   inputVec:  row or column vector of complex matlab doubles holding the 
%      data to be written into DMEM at startAddr.  Each entry in 
%      inputVector corresponds to one complex value of the specified 
%      precision.
%
%   precision:  string specifying the precision to use when interpreting
%      the data in inputVector.  The options are:
%       'uint':  
%       'half_fixed':
%       'half':
%       'single':
%       'double':
%
% OUTPUT:
%
%   dmemOut:  updated struct representing DMEM with inputVector loaded.
%
% EXAMPLE USE:
%   A typical calling sequence using the dmem access layer looks something
%   like this:
%       dram = dmemCreate(startAddr, MEM__ld_rodata_bottom);
%       dram = dmemWriteReal   (dram, MEM_x_buffer, x_be,   'half_fixed' );
%       dram = dmemWriteComplex(dram, MEM_y_buffer, y_be,   'single' );
%       dram = dmemWriteReal   (dram, MEM_ctrlVar, ctrlVar, 'uint' );
%       dmemSaveHexFile(dram, inFileName);
%       ... Run ISS ...
%             overwrite dram  <2*startAddr> inFileName
%             ...
%             save dram outFileName   <startAddr>  <endAddr>
%       dramOut = dmemReadHexFile( outFileName, startAddr );
%       x_mc = dmemReadReal   (dramOut, MEM_x_buffer, SIZ_x_buffer*2, 'half_fixed')
%       y_mc = dmemReadComplex(dramOut, MEM_y_buffer, SIZ_y_buffer/2, 'single' );
%
%
% SEE ALSO:
%      dmemCreate, 
%      dmemWriteReal, dmemSaveHexFile,
%      dmemReadReal,  dmemReadComplex,  dmemReadHexFile
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.
     


% dmemIn struct - for internal use:   
%   base  ( full-word address pointing to first word )
%   data  ( column vector holding storage data: one uint32 per memory location )


% Verify that inputVec is a complex vector and convert it to column form for use
if ( size(inputVec,1) ~= 1  && size(inputVec,2) ~= 1 )
    error('dmemWriteComplex requires a row or column vector for inputVec');
end
if ( size(inputVec,2) > size(inputVec,1) )
    inputVec = inputVec.';  % convert from row to column vector
end

% Convert inputVec to a real vector and use dmemWriteReal to fill dmemIn
% image at the specified startAadr location with inputVec based on precision setting
realVec = zeros(2*length(inputVec),1);    
realVec(1:2:end) = real(inputVec);
realVec(2:2:end) = imag(inputVec);

dmemOut = dmemWriteReal(dmemIn, startAddr, realVec, precision);

return



    
    
    
    
    
    
