% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function outputVec = dmemReadReal(dmemIn, startAddr, numValues, precision)
% Dmem access utility for reading a real vector out of dmemIn image at 
% the specified starting address using the specified precision.  
%
% INPUTS:
%
%   dmemIn:  struct representing DMEM.  Usually generated by a call to 
%      dmemCreate().  Internal details of this structure only matter to
%      the dmem access layer implementation.
%
%   startAddr:  full-word DMEM address (integer) pointing to the first word
%      of storage for inputVector.
%
%   numValues: number of real values of the specified precision to read 
%      from DMEM.  The number of full-word memory locations read will 
%      depend on the precision.  For example, 
%           dmemReadReal(dmemIn, 100, 10, 'double') 
%      would read 20 full-words to generate an outputVec containing 
%      10 real doubles.
%
%   precision:  string specifying the precision to use when interpreting
%      the data in inputVector.  The options are:
%       'uint':  
%       'half_fixed':
%       'half':
%       'single':
%       'double':
%
% OUTPUT:
%
%   outputVec:  real vector (numValues x 1) of matlab doubles
%      precision-limited according to specified precision
%
% EXAMPLE USE:
%   A typical calling sequence using the dmem access layer looks something
%   like this:
%       dram = dmemCreate(startAddr, MEM__ld_rodata_bottom);
%       dram = dmemWriteReal   (dram, MEM_x_buffer, x_be,   'half_fixed' );
%       dram = dmemWriteComplex(dram, MEM_y_buffer, y_be,   'single' );
%       dram = dmemWriteReal   (dram, MEM_ctrlVar, ctrlVar, 'uint' );
%       dmemSaveHexFile(dram, inFileName);
%       ... Run ISS ...
%             overwrite dram  <2*startAddr> inFileName
%             ...
%             save dram outFileName   <startAddr>  <endAddr>
%       dramOut = dmemReadHexFile( outFileName, startAddr );
%       x_mc = dmemReadReal   (dramOut, MEM_x_buffer, SIZ_x_buffer*2, 'half_fixed')
%       y_mc = dmemReadComplex(dramOut, MEM_y_buffer, SIZ_y_buffer/2, 'single' );
%
% SEE ALSO:
%      dmemCreate, 
%      dmemWriteReal, dmemWriteComplex, dmemSaveHexFile,
%      dmemReadComplex,  dmemReadHexFile
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.
     


% dmemIn struct - for internal use:  
%   base  ( full-word address pointing to first word )
%   data  ( column vector holding storage data: one uint32 per memory location )


% Find the number of memory words required and verify that it fits
numWords = numValues;
if strcmp(precision, 'half_fixed') || strcmp(precision, 'half')
    numWords = numWords/2;
end
if strcmp(precision, 'double')
    numWords = numWords*2;
end

startAddr = startAddr - dmemIn.base;   % convert startAddr to local address within image
if startAddr < 0
    error( sprintf('startAddr %d is not in image\n',startAddr) );
end
if (startAddr + numWords - 1) > length(dmemIn.data)
    error( sprintf('requested data exceeds size of dmem Image contents at startAddr %d\n',startAddr) );
end


% Generate dmemOut starting with a copy of dmemIn and filling the 
% specified startAadr location with inputVec based on precision setting
outputVec = zeros(numValues,1);
startIndex = startAddr + 1;
endIndex   = startAddr + numWords;
switch precision
    case 'uint'
        outputVec = dmemIn.data( startIndex:endIndex );
        
    case 'half_fixed'
        rep32 = dmemIn.data( startIndex:endIndex );
        rep16 = zeros(numValues,1);
        loHalfWordMask = hex2dec('ffff');
        rep16(1:2:end) = bitand( rep32, loHalfWordMask );
        rep16(2:2:end) = floor(rep32/2^16);
        
        outputVec = r_cust2dbl(uint64(rep16), 0);

    case 'half'
        rep32 = dmemIn.data( startIndex:endIndex );
        rep16 = zeros(numValues,1);
        loHalfWordMask = hex2dec('ffff');
        rep16(1:2:end) = bitand( rep32, loHalfWordMask );
        rep16(2:2:end) = floor(rep32/2^16);
        
        outputVec = r_cust2dbl(uint64(rep16), 1);
        
    case 'single'
        rep = dmemIn.data( startIndex:endIndex );
        s = bitand( rep, hex2dec('80000000')) /2^31;
        m = bitand( rep, hex2dec('007fffff')) /2^23;
        e = bitand( rep, hex2dec('7f800000')) /2^23;
        outputVec = ( ( s >  0 ) .* ( -1 - m ) .* 2.^(e-127) + ...
                      ( s == 0 ) .* (  1 + m ) .* 2.^(e-127) );
        outputVec = ( ~and( and(m==0, s==0), e==0) ) .* outputVec;  % handle zero exception 
    case 'double'
        outputVec = typecast(uint32( dmemIn.data( startIndex:endIndex ) ),'double');
        
    otherwise
        error('unrecognized precision');
end

return



    
    
    
    
    
    
