% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function dmemSaveHexFile(dmemIn, inFileName)
% Dmem access utility to generate a hex file from the dmemIn image suitable
% for loading into the ISS DMEM via the overwrite dram command.
%
% INPUTS:
%
%   dmemIn:  struct representing DMEM.  Usually generated by a call to
%      dmemCreate().  Internal details of this structure only matter to
%      the dmem access layer implementation.
%
%   inFileName: string containing the name (and path if necessary) of the
%      hex file to generate.
%
%
% EXAMPLE USE:
%   A typical calling sequence using the dmem access layer looks something
%   like this:
%       dram = dmemCreate(startAddr, MEM__ld_rodata_bottom);
%       dram = dmemWriteReal   (dram, MEM_x_buffer, x_be,   'half_fixed' );
%       dram = dmemWriteComplex(dram, MEM_y_buffer, y_be,   'single' );
%       dram = dmemWriteReal   (dram, MEM_ctrlVar, ctrlVar, 'uint' );
%       dmemSaveHexFile(dram, inFileName);
%       ... Run ISS ...
%             overwrite dram  <2*startAddr> inFileName
%             ...
%             save dram outFileName   <startAddr>  <endAddr>
%       dramOut = dmemReadHexFile( outFileName, startAddr );
%       x_mc = dmemReadReal   (dramOut, MEM_x_buffer, SIZ_x_buffer*2, 'half_fixed')
%       y_mc = dmemReadComplex(dramOut, MEM_y_buffer, SIZ_y_buffer/2, 'single' );
%
% SEE ALSO:
%      dmemCreate,
%      dmemWriteReal, dmemWriteComplex,
%      dmemReadReal,  dmemReadComplex,  dmemReadHexFile
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.



% dmemIn struct - for internal use:
%   base  ( full-word address pointing to first word )
%   data  ( vector holding storage data: one uint32 per memory location )


[fid, msg] = fopen(inFileName, 'wt');
if -1 == fid
error( msg );
end
fprintf(fid, '0x%08x,\n', dmemIn.data );
fclose(fid);









