% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function dmem = dmemInit(filename, dmemsize, type)
% Dmem access utility for reading the data memory image file generated by VSP
% ELF32 toolchain utility vspa-elf2hex.
%
% INPUTS:
%
%   filename: string containing the name (and path if necessary) of a
%       hex file generated by the vspa-elf2hex command line tool.
%
%   dmemsize (optional): size (in 32-bit words) of the data memory.
%
%   type (optional): specifies how to initialize uninitialized data memory.
%       May be one of the following:
%         - 'zero' to initialize data memory to 0.
%         - 'random' to initialize data memory with random values.
%
% OUTPUT:
%
%   dmem:  dmem image (dmem access layer structure) representing the data memory
%       where all values are random, except the ones initialized from <filename>.
%
% EXAMPLE USE:
%
%    Matlab:
%       ...
%       dram = dmemInit('vspa_vdata.hex', 128*1024/4, 'random' );
%       dram = dmemWriteReal( dram, MEM_variable, variable, 'uint' );
%       dram = dmemWriteComplex( dram, MEM_buffer, buffer, 'single' );
%       dmemSaveHexFile( dram, 'vspa_dram.hex' );
%       ...
%
% SEE ALSO:
%      dmemCreate,
%      dmemWriteReal, dmemWriteComplex, dmemSaveHexFile,
%      dmemReadReal,  dmemReadComplex
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.

if 1 == nargin
    dmemsize = 512*1024/4;      % 512 KiB by default.
    type = 'random';
elseif 2 == nargin
    type = 'random';
end

dmem = struct;
dmem.base = 0;

[fid, msg] = fopen( filename, 'rt' );
if -1 == fid
    error( msg );
end
dataStrs = textscan( fid, '%8s\n' );
if strcmp( type, 'random' )
    dmem.data = randi( 2^32 - 1, dmemsize, 1 );
else
    dmem.data = zeros( dmemsize, 1 );
end
dmem.data(dmem.base+1:dmem.base+length( dataStrs{1} )) = hex2dec( dataStrs{1} );
fclose( fid );

return;
