% SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
% Copyright 2020 - 2025 the original authors
function dmemAppendHexFile(dmemIn, inFileName)
% Dmem access utility to add to a hex file from the dmemIn image suitable
% for loading into the ISS DMEM via the overwrite dram command.
%
% INPUTS:
%
%   dmemIn:  struct representing DMEM.  Usually generated by a call to
%      dmemCreate().  Internal details of this structure only matter to
%      the dmem access layer implementation. A number may also be passed
%       which will be converted to hex and appended. A String will be 
%       interpreted as hex and either trimmed if too long or zero padded
%       if too short.
%
%   inFileName: string containing the name (and path if necessary) of the
%      hex file to generate.
%
%
% EXAMPLE USE:
%   A typical calling sequence using the dmem access layer looks something
%   like this:
%       dram = dmemCreate(startAddr, MEM__ld_rodata_bottom);
%       dram = dmemWriteReal   (dram, MEM_x_buffer, x_be,   'half_fixed' );
%       dram = dmemWriteComplex(dram, MEM_y_buffer, y_be,   'single' );
%       dram = dmemWriteReal   (dram, MEM_ctrlVar, ctrlVar, 'uint' );
%       dmemAppendHexFile(dram, inFileName);
%   or  dmemAppendHexFile(5, inFileName);
%   or  dmemAppendHexFile('FFFFEEEE', inFileName);
%
% NOTE: This utility is PRELIMINARY and SUBJECT TO CHANGE.


% dmemIn struct - for internal use:
%   base  ( full-word address pointing to first word )
%   data  ( vector holding storage data: one uint32 per memory location )


[fid, msg] = fopen(inFileName, 'at');
if -1 == fid
error( msg );
end

if( isa( dmemIn, 'struct'))
    fprintf(fid, '%08x\n', dmemIn.data );
elseif( isa( dmemIn, 'numeric'))
    fprintf(fid, '%08x\n', dmemIn );
else
    % trim string if > 8 chars... pad string with zeros if < 8 chars
    if( length( dmemIn ) > 8 )
        dmemIn = dmemIn(( length( dmemIn ) - 7): length( dmemIn ))
    elseif ( length( dmemIn ) < 8 )
        dmemIn = sprintf('%08s', dmemIn);
    end
    fprintf(fid, '%s\n', dmemIn );
end
fclose(fid);









